name: StationCode

on:
  push:
    branches: 
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: station_code

jobs:
  get-station-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install beautifulsoup4
      - name: Install dependencies
        run: pip install requests
      - name: Run Python
        run: python get_station_code.py
