name: StationCode

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install beautifulsoup4
      - name: Run Python
        run: python station_code/get_station_code.py
